--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/J0k3rrWild/ChatRewardEvent
build-by-default: true
branches:
- api4
projects:
  ChatRewardEvent:
    path: ""
    icon: "icon.png"
...
