Time: 60   # 60 = the code will show up every 60 secounds
Length: 10 #  Code length
Characters: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" # Allowed strings
win-message: "[ChatRewardEvent] > Bravo! You get " # Win message, after the word get, the number of items and the name will be displayed
code-message: "[ChatRewardEvent] > Rewrite the code to receive the prize: " # After the sign ":" a code will be displayed